# Generated by Django 5.2.4 on 2025-07-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedcv",
            name="user",
        ),
    ]
