# Generated by Django 5.2.4 on 2025-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_remove_uploadedcv_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedcv",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="uploadedcv",
            name="pdf",
            field=models.FileField(upload_to="cvs/"),
        ),
    ]
